export const BOARD_ADDED = "BOARD_ADDED"

export const LIST_ADDED = "LIST_ADDED"
export const LIST_NAME_EDITED = "LIST_NAME_EDITED"

export const CARD_ADDED = "CARD_ADDED"
export const CARD_TITLE_EDITED = "CARD_TITLE_EDITED"
export const CARD_DESC_EDITED = "CARD_DESC_EDITED"
export const CARD_REMOVED = "CARD_REMOVED"